services:
  tic-tac-toe:
    image: "zcohn93/tic-tac-toe:0.6"
    container_name: tic-tac-toe
    ports:
      - 4001:4001
    environment:
      - PORT=4001
    secrets:
      - db_user
      - db_pw
      - session_secret
    tty: true
    stdin_open: true
    volumes:
      - ./secrets/.netrc:/root/.netrc:ro

secrets:
  github_token:
    file: secrets/.netrc
  db_user:
    file: secrets/db_user
  db_pw:
    file: secrets/db_pw
  session_secret:
    file: secrets/session_secret
