services:
  tic-tac-toe:
    image: "zcohn93/tic-tac-toe:0.4"
    container_name: tic-tac-toe
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - NETRC="/run/secrets/github_token"
    secrets:
      - github_token
      - db_user
      - db_pw
    tty: true
    stdin_open: true

secrets:
  github_token:
    file: secrets/.netrc
  db_user:
    file: secrets/db_user
  db_pw:
    file: secrets/db_pw
