services:
  tic-tac-toe:
    image: "zcohn93/tic-tac-toe:0.9"
    container_name: tic-tac-toe
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - DB_URI=tic-tac-toe.blziyjp.mongodb.net/tic-tac-toe
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    secrets:
      - db_user
      - db_pw
      - jwt_secret
      - jwt_refresh_secret
    depends_on:
      - redis-db
    tty: true
    stdin_open: true

  tic-tac-toe-frontend:
    image: "zcohn93/tic-tac-toe-frontend:0.3"
    container_name: tic-tac-toe-frontend
    ports:
      - 5173:5173
    tty: true
    stdin_open: true

  redis-db:
    image: "redis:latest"
    container_name: "redis"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - ~/redis/data:/data
    ports:
      - 6379:6379

secrets:
  db_user:
    file: secrets/db_user
  db_pw:
    file: secrets/db_pw
  jwt_secret:
    file: secrets/jwt_secret
  jwt_refresh_secret:
    file: secrets/jwt_refresh_secret
