services:
  tic-tac-toe:
    image: "zcohn93/tic-tac-toe:0.7"
    container_name: tic-tac-toe
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - DB_URI=tic-tac-toe.blziyjp.mongodb.net/tic-tac-toe
    secrets:
      - db_user
      - db_pw
      - jwt_secret
      - jwt_refresh_secret
      - session_secret
    tty: true
    stdin_open: true
    volumes:
      - ./secrets/.netrc:/root/.netrc:ro

  tic-tac-toe-frontend:
    image: "zcohn93/tic-tac-toe-frontend:0.2"
    container_name: tic-tac-toe-frontend
    ports:
      - 5173:5173
    tty: true
    stdin_open: true

secrets:
  github_token:
    file: secrets/.netrc
  db_user:
    file: secrets/db_user
  db_pw:
    file: secrets/db_pw
  jwt_secret:
    file: secrets/jwt_secret
  jwt_refresh_secret:
    file: secrets/jwt_refresh_secret
  session_secret:
    file: secrets/session_secret
