const express = require('express');
const { append } = require('express/lib/response');
const bcrypt = require('bcrypt');
const { users } = require('../db/users');
const { checkNotAuthenticated } = require('../server/passport-cfg');
const router = express.Router();
const NUM_HASHES = 10;

router.get('/', checkNotAuthenticated, (req, res) => {
    res.render('register.ejs');
});

router.post('/', checkNotAuthenticated, async (req, res) => {
    try {
        // TODO: Consider changing from NUM_HASHES to salt
        const hashedPassword = await bcrypt.hash(req.body.password, NUM_HASHES);
        users.push({
            // This will be generated by DB in future
            id: Date.now().toString(),
            name: req.body.name,
            email: req.body.email,
            password: hashedPassword
        });
        // Redirect to login after successful registration
        res.redirect('/login');
    } catch (err) {
        console.log(err);
        res.redirect('/register');
    }
    console.log(users);
});

module.exports = router;
